### ISSUE TITLE
Dynamically control speed

### ISSUE THREAD

**Issue by majorlennox** [arduino-libraries/Stepper#14]
Is it possible to control the speed of a stepper motor with an a4988 driver dynamically? I would like to realize a control system on an arduino, using speed and not position control.
Thanks in advance!

**Comment by per1234** [comment]
Hi @majorlennox. This library is not designed for use with stepper motor drivers that have the step/direction interface like the A4988.

This topic is more appropriate for the Arduino Forum. I'm sure we'll be able to help you with your problem over there.

Please do this:
1. Read http://forum.arduino.cc/index.php?topic=148850
2. If you haven't already done so, create a new thread in the appropriate section of the forum (http://forum.arduino.cc/), following all the rules.
