### ISSUE TITLE
Small notation error in comment.

### ISSUE THREAD

**Issue by Lyoko2696** [arduino-libraries/Stepper#31]
Hi!
It's nothing serious but I got a little distracted in my work rechecking how micro() worked because of it.

So just to let you know that in line 105 in "Stepper.h", the comment says "// delay between steps, in ms, based on speed".
"ms" is short for millisecond, the correct abbreviation for microsecond is "µs" or for easier typing "us".

Reference:
https://simple.wikipedia.org/wiki/Second

Thank you for your time!

**Comment by per1234** [comment]
Thanks @Lyoko2696. Please submit a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork) for the correction and I'll be sure to accept it.
